# https://github.com/CodingItWrong/rails-docker-mac
postgres:
  image: postgres
  ports:
    - "5432:5432"
  volumes:
    - ./tmp/db:/var/lib/postgresql/data
web:
  build: .
  volumes:
    - .:/usr/src/app
  ports:
    - "3000:3000"
  links:
    - postgres
